project:
  type: website
  output-dir: docs
  
website:
  title: "Jack Freimann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jack-freimann-03a238260/

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

